<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-firebats2000/blob/main/more_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [ ]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [ ]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'

np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [ ]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [ ]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [ ]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 1.51206697e+00, -2.47558549e-01,  8.42581568e-01],
        [ 9.17513121e-01,  8.97613967e-01,  8.55399214e-01],
        [ 2.12851749e+00,  4.58876157e-01,  1.29746926e-03]]),
 array([[4.72923935e-01, 4.62282074e-02, 5.22636023e-01],
        [9.52599204e-01, 8.22670459e-01, 6.36687541e-01],
        [6.73444421e-01, 9.51453466e-04, 1.04725275e-01]]))

In [ ]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.

A = np.random.rand(5, 5)

# A symmetric matrix A satisfies A = 0.5*(A + A.T);

A_sym = 0.5 * (A + A.T)

# An antisymmetric matrix satisfies A = 0.5*(A - A.T);

A_asym = 0.5 * (A - A.T)

# The `.T` attribute finds the transpose of the matrix.

print("Original matrix A:\n", A)
print("\nSymmetric part (A_sym):\n", A_sym)
print("\nAntisymmetric part (A_asym):\n", A_asym)

Original matrix A:
 [[0.41785903 0.25590426 0.74688351 0.27009809 0.07789227]
 [0.69835141 0.45381071 0.27918022 0.88844551 0.34659617]
 [0.9856503  0.19561685 0.13745326 0.6275365  0.19439515]
 [0.46462475 0.77201186 0.34042006 0.41609844 0.66787885]
 [0.4321554  0.79103335 0.91927286 0.65913876 0.26780462]]

Symmetric part (A_sym):
 [[0.41785903 0.47712783 0.86626691 0.36736142 0.25502384]
 [0.47712783 0.45381071 0.23739853 0.83022868 0.56881476]
 [0.86626691 0.23739853 0.13745326 0.48397828 0.55683401]
 [0.36736142 0.83022868 0.48397828 0.41609844 0.66350881]
 [0.25502384 0.56881476 0.55683401 0.66350881 0.26780462]]

Antisymmetric part (A_asym):
 [[ 0.         -0.22122357 -0.1193834  -0.09726333 -0.17713156]
 [ 0.22122357  0.          0.04178169  0.05821682 -0.22221859]
 [ 0.1193834  -0.04178169  0.          0.14355822 -0.36243885]
 [ 0.09726333 -0.05821682 -0.14355822  0.          0.00437005]
 [ 0.17713156  0.22221859  0.36243885 -0.00437005  0.        ]]


## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [ ]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [ ]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [ ]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

np.matmul?
np.dot?

# np.matmul is a strict matrix multiplication taht behaves like a mathematical multiplication.
# Works with 2D arrays and stack matrices but 1D arrays require promotion in order to work.
# np.dot is a dot product with behaviors that depend on input:
# If both are 1D vectors it returns as a scalar dot product, 2D returns as a matrix multiplication
# @ is shorthand for np.matmul that follows matrix multiplication rules but not dot product rules.
# * multiplies element by element and not matrices.

# Examples (2D arrays):

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)
print(A * B)

# np.matmul and @ are the same, np.dot behaved like a matrix multiplication because there were 2D arrays while * only multiplied element by element.

# Example (1D arrays):

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# np.matmul(x, y)  # ERROR
print(np.dot(x, y))
print(x * y)

# For 1D arrays, np.matmul and @ give an error, np.dot returned a single number as a dot product and * multiplied element by element.

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
32
[ 4 10 18]


## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [ ]:
import math

In [ ]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

The slowest run took 4.48 times longer than the fastest. This could mean that an intermediate result is being cached.
451 ms ± 295 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [ ]:
%%timeit
y_vec = np.sin(xs)

NameError: name 'xs' is not defined

In [ ]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

The `%%timeit` magic command is used to measure the execution time of a Python statement or expression. It automatically runs the code multiple times to provide a more accurate average time and standard deviation, which helps in benchmarking performance. It's especially useful for comparing the efficiency of different code snippets.

In [ ]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

def total_energy(x, v, m=1.0, k=1.0):
    return 0.5 * m * v**2 + 0.5 * k * x**2

x = np.linspace(-10, 10, 1_000_000)
v = np.linspace(-5, 5, 1_000_000)

%timeit  #Tried using %%tiemit but got the error: UsageError: Line magic function `%%timeit` not found. Used %timeit instead but not sure if theres suppose to be a difference
total_energy(x, v)

array([62.5    , 62.49975, 62.4995 , ..., 62.4995 , 62.49975, 62.5    ])

## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [ ]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [ ]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

# vecs[:, 0] is the eigenvector for vals[0]
# vecs[:, 1] is the eigenvector for vals[1]
# vecs[:, 2] is the eigenvector for vals[2]

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [ ]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [ ]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [ ]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [ ]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.

A = np.random.rand(2, 2)
Q, R = np.linalg.qr(A)
UU_T = Q @ Q.T
U_TU = Q.T @ Q
print(Q, R )
print("Q @ Q.T =\n", np.round(UU_T, decimals=10))
print("Q.T @ Q =\n", np.round(U_TU, decimals=10))

[[-0.89414561 -0.44777632]
 [-0.44777632  0.89414561]] [[-0.85316034 -0.59426842]
 [ 0.          0.2782588 ]]
Q @ Q.T =
 [[ 1. -0.]
 [-0.  1.]]
Q.T @ Q =
 [[ 1. -0.]
 [-0.  1.]]


In [ ]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.

# Example 2x2 symmetric matrix
K = np.array([[2, -1],
              [-1, 2]])

# Compute eigenvalues and eigenvectors
vals, U = np.linalg.eigh(K)  # U = [v1, v2], orthonormal

Lambda = U.T @ K @ U

print("Eigenvalues from np.linalg.eigh:\n", vals)
print("\nDiagonal matrix U.T @ K @ U:\n", np.round(Lambda, 10))

# U contains orthonormal eigenvectors of K. U.T @ K @ U diagonalizes K. This confirms the relation: λ = U.T @ K @ U. where λ is the diagonal matrix of eigenvalues.

Eigenvalues from np.linalg.eigh:
 [1. 3.]

Diagonal matrix U.T @ K @ U:
 [[ 1. -0.]
 [ 0.  3.]]


In [ ]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

# Spring constant
k = 1.0

# 2x2 "force constant" matrix for a diatomic molecule
K = np.array([[ k, -k],
              [-k,  k]])

# Eigen decomposition
vals, U = np.linalg.eigh(K)

print("Eigenvalues:", vals)
print("Eigenvectors (columns):\n", U)



Eigenvalues: [0. 2.]
Eigenvectors (columns):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
